version: "3"
services:
  app:
    build:
      context: ./app/
    environment:
      - PYTHONUNBUFFERED=1
    restart: on-failure

  app-db:
    image: postgres:13
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_USER: artem_neronov
      POSTGRES_DB: neuro_bot
      
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    restart: on-failure
volumes:
  postgres_volume:
